version: '3.8'

services:
  backend:
    image: qlda-backend:latest
    build:
      context: .
      dockerfile: demo1/Dockerfile
    container_name: qlda-backend-container
    ports:
      - "64950:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=qlda-postgres-container;Port=5432;Database=QLDA;Username=quangmd;Password=31122001;
      - Database__AutoMigrate=false
      - Database__SeedSampleData=true
    networks:
      - qlda-network
    restart: always

networks:
  qlda-network:
    external: true
