services:
  backend:
    image: qlda-backend:latest
    build:
      context: .
      dockerfile: demo1/Dockerfile
    container_name: qlda-backend-container
    ports:
      - "64950:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST:-10.225.11.156};Port=${DB_PORT:-5432};Database=${DB_NAME:-QLDA};Username=${DB_USER:-quangmd};Password=${DB_PASSWORD:-31122001};
      - Database__AutoMigrate=false
      - Database__SeedSampleData=true
      - Auth__EnableDevBypass=true
      - Auth__EnableLocalPasswordLogin=true
      - Radius__Enabled=false
    restart: always
